In [1]:
import datasets

In [2]:
ds = datasets.load_dataset("theelderemo/genius-lyrics-cleaned", cache_dir="./hf_cache")

In [3]:
df = ds["train"].to_pandas()
df.head()

df.info()

df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 3179588 entries, 0 to 3179587
Data columns (total 5 columns):
 #   Column  Dtype
---  ------  -----
 0   title   str
 1   artist  str
 2   tag     str
 3   year    int64
 4   lyrics  str
dtypes: int64(1), str(4)
memory usage: 4.6 GB

               year
count  3.179588e+06
mean   2.010573e+03
std    4.125201e+01
min    1.000000e+00
25%    2.008000e+03
50%    2.016000e+03
75%    2.019000e+03
max    2.100000e+03

In [4]:
df[df["artist"].str.lower() == "gojira"]

,title,artist,tag,year,lyrics
23302,Flying Whales,Gojira,rock,2005,[Verse 1]\nWaters of chaos have invaded all sp...
26851,Stranded,Gojira,rock,2016,[Verse 1]\nA growing sickness in the heart\nDe...
29840,Lenfant sauvage,Gojira,rock,2012,[Verse 1]\nSo long I've been trying to match\n...
32439,Silvera,Gojira,rock,2016,[Verse 1]\nQuit moaning about fate and change\...
36099,The Art of Dying,Gojira,rock,2008,"[Verse 1]\nBreathing slowly, mechanical heartb..."
...,...,...,...,...,...
1000782,Sentenced to Life,Gojira,rock,1996,Out in trash streets in the city\nLosers of th...
1058371,Escape,Gojira,pop,2015,"Feel no pain, but my life ain't easy\nI know I..."
1243718,On the B.O.T.A. Demo,Gojira,rock,1999,"Lost, a lion came and said:\n""Come, on the bri..."
1374662,Deliverance Demo,Gojira,rock,1999,"Your words are so cold to me\nIndisposed, don'..."
1973980,Maciste 14,Gojira,rock,2003,[???]\n\n[???]\n\nBut I got a neighbor there\n...

In [5]:
df["artist"].value_counts().head(50)

artist
Genius English Translations    13572
The Grateful Dead               2014
Lil B                           1304
Gucci Mane                      1233
Frank Zappa                     1198
Lil Wayne                       1197
Guided by Voices                1183
Tendon Levey                    1173
Juice WRLD                      1164
KIDZ BOP Kids                   1161
Johnny Cash                     1029
Muze Sikk                        967
Madonna                          948
Frank Sinatra                    946
Chief Keef                       921
Willie Nelson                    921
OCTOBERSFULLMOON                 920
YOUNG DIAMOND                    884
Bob Dylan                        850
Chris Brown                      838
Prince                           831
The Rolling Stones               829
Kanye West                       818
George Jones                     801
Vybz Kartel                      791
David Bowie                      788
Elvis Presley                    782
BONES                            778
Soulja Boy                       773
Young Thug                       767
The Beatles                      751
Depeche Mode                     736
Snoop Dogg                       725
Glee Cast                        725
The Game                         718
Ella Fitzgerald                  712
Merle Haggard                    706
YoungBoy Never Broke Again       703
Van Morrison                     702
Dolly Parton                     689
The Mountain Goats               686
Curren$y                         681
Insane Clown Posse               675
Bruce Springsteen                653
Aretha Franklin                  651
Wiz Khalifa                      648
They Might Be Giants             647
Mariah Carey                     646
Paul McCartney                   645
Cliff Richard                    645
Name: count, dtype: int64

In [10]:
print(df[df["artist"] == "Frank Zappa"]["lyrics"].iloc[2])

[Liner Note 1]
A boring old garage in a residential area with a teen-age band rehearsing in it. JOE (the main character in the CENTRAL SCRUTINIZER'S Special Presentation) sings to us of the trials and tribulations of garage-band husbandry...

[Intro]
We take you now, to a garage, in Canoga Park...
(It makes its own sauce...)

[Verse 1: Joe]
It wasn't very large
There was just enough room to cram the drums
In the corner over by the Dodge
It was a fifty-four
With a mashed up door
And a cheesy little amp
With a sign on the front said "Fender Champ"
And a second hand guitar
It was a Stratocaster with a whammy bar

[Liner Note 2]
At this point, LARRY (a guy who will eventually give up music and earn a respectable living as a roadie for a group called Toad-O) joins in the song...
[Chorus]
We could jam in Joe's Garage
His mama was screamin'
His dad was mad
We was playin' the same old song
In the afternoon 'n' sometimes we would
Play it all night long
It was all we knew, 'n' easy too
So we wouldn't get it wrong
All we did was bend the string like...

[Verse 2: Larry]
Hey!
Down in Joe's Garage
We didn't have no dope or LSD
But a coupla quarts'a beer
Would fix it so the intonation
Would not offend your ear
And the same old chords goin' over 'n' over
Became a symphony
We would play it again 'n' again 'n' again
Cause it sounded good to me
One more time!

[Chorus]
We could jam in Joe's Garage
His mama was screaming
"Turn it down!"
We was playing' the same old song
In the afternoon 'n' sometimes we would
Play it all night long
It was all we knew, and easy too
So we wouldn't get it wrong
Even if you played it on the saxophone
[Verse 3: Larry & Liner Note 3]
We thought we was pretty good
We talked about keepin' the band together
'N' we figured that we should
Cause about this time we was gettin' the eye
From the girls in the neighborhood
They'd all come over 'n' dance around
Like...
(Twenty teen-age girls dash
In and go STOMP-CLAP
STOMP-CLAP-CLAP...)
So we picked out a stupid name
Had some cards printed up for a couple 'a bucks
'N' we was on our way to fame
Got matching suits 'N' Beatle Boots
'N' a sign on the back of the car
'N' we was ready to work in a Go-Go bar

[Bridge]
One, two, three, four
Let's see if you got some more!

[Verse 4: Larry & Joe]
People seemed to like our song
They got up 'n' danced 'n' made a lotta noise
An' it wasn't 'fore very long
A guy from a company we can't name
Said we ought'a take his pen
'N' sign on the line for a real good time
But he didn't tell us when
These "good times" would be somethin'
That was really happenin'
So the band broke up
An' it looks like
We will never play again
Guess you only get one chance in life
To play a song that goes like...
[Liner Note 4]
*And, as the band plays their little song
MRS. BORG (who keeps her son SY
In the closet with the vacuum cleaner)
Screams out the window...*

[Bridge]
Turn it down!
Turn it DOWN!
I have children sleeping here...
Don't you boys know any nice songs?

[Verse 5: Joe]
Well the years was rollin' by, yeah
Heavy Metal 'n' Glitter Rock
Had caught the public eye, yeah
Snotty boys with lipstick on
Was really flyin' high, yeah
'N' then they got that Disco thing
'N' New Wave came along
'N' all of a sudden I thought the time
Had come for that old song
We used to play in "Joe's Garage"
And if I am not wrong
You will soon be dancin' to the-

[Bridge]
The White Zone is for loading and unloading only
If you gotta load or unload, go to the White Zone

[Outro]
Well the years was rollin' by
The years were rollin' by (I'm calling the police!)
The years were rollin' by
The years were rollin' by (I did it! They'll be here, shortly!)
The years were rollin' by (This is the police...)
(I'm not joking around anymore!)
The years was rollin' by (We have the garage surrounded)
(Give yourself up)
(We will not harm you, or hurt you neither)
The years were rollin' by
You'll see them, there they are, they're coming!)
(This is the police)
The years were rollin' by
(Give yourself up)
(We will not harm you)
(Listen to that mess, would you?)
(This is the police, give yourself up)
(We have the garage surrounded!)
(Everyday this goes on around here!)
The years were rollin' by
(We will not harm you, or maim you)
The years were rollin' by
(SWAT Team 4, move in!)
(He used to cut my grass! He was a very nice boy!)
(This is the police, come out with your hands up!)
(That's disgusting...)

[Outro]
This is the Central Scrutinizer...
That was Joe's first confrontation with "The Law"...
Naturally, we were easy on him
One of our friendly counsellors gave him a donut
And told him to stick closer
To church-oriented social activities...

In [11]:
df[df["artist"] == "Frank Zappa"]["title"].value_counts().head(20)

title
Bobby Brown Goes Down           1
Valley Girl                     1
Joes Garage                     1
Catholic Girls                  1
Muffin Man                      1
Jewish Princess                 1
Uncle Remus                     1
Dinah-Moe Humm                  1
Camarillo Brillo                1
Why Does It Hurt When I Pee?    1
Stick It Out                    1
Cosmik Debris                   1
Fembot in a Wet T-Shirt         1
Willie the Pimp                 1
Crew Slut                       1
I’m The Slime                   1
Montana                         1
Nanook Rubs It                  1
The Central Scrutinizer         1
Dont Eat the Yellow Snow        1
Name: count, dtype: int64

In [12]:
df["lyrics"].str.extractall(r"\[([^\]]+)\]")[0].value_counts().head(50)

0
Chorus                2251164
Verse 1                774242
Verse 2                736087
Hook                   514647
?                      511497
Outro                  427605
Bridge                 418060
Intro                  395141
Pre-Chorus             342180
Verse                  244272
Verse 3                206286
Post-Chorus             87618
Refrain                 79725
Verse 4                 51971
Interlude               49373
Chorus 2                42811
Chorus 1                41101
Instrumental            26352
Drop                    25953
x2                      17355
Instrumental Break      16866
Pre-Chorus 2            16689
Verse 5                 16278
Pre-Chorus 1            16066
HOOK                    13729
Verse 1:                13036
Guitar Solo             12500
Break                   12375
Verse 2:                12306
Pre Chorus              11311
Chorus 3                10821
Pre-Hook                10235
Breakdown                9419
Hook x2                  8511
Verse One                7724
hook                     7561
Spoken                   7395
Solo                     7288
Chorus x2                7262
Verse 6                  7179
Verse Two                7071
VERSE 1                  6730
Bridge 2                 6625
VERSE 2                  6394
Chrous                   6179
VERSE                    5968
x4                       5675
Sample                   5623
Bridge 1                 5550
verse                    5371
Name: count, dtype: int64