In [2]:
import datasets

In [3]:
ds = datasets.load_dataset("theelderemo/genius-lyrics-cleaned", cache_dir="./hf_cache")

In [4]:
df = ds["train"].to_pandas()
df.head()

df.info()

df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 3179588 entries, 0 to 3179587
Data columns (total 5 columns):
 #   Column  Dtype
---  ------  -----
 0   title   str
 1   artist  str
 2   tag     str
 3   year    int64
 4   lyrics  str
dtypes: int64(1), str(4)
memory usage: 4.6 GB

               year
count  3.179588e+06
mean   2.010573e+03
std    4.125201e+01
min    1.000000e+00
25%    2.008000e+03
50%    2.016000e+03
75%    2.019000e+03
max    2.100000e+03

In [10]:
df[df["artist"].str.lower() == "gojira"]

,title,artist,tag,year,lyrics
23302,Flying Whales,Gojira,rock,2005,[Verse 1]\nWaters of chaos have invaded all sp...
26851,Stranded,Gojira,rock,2016,[Verse 1]\nA growing sickness in the heart\nDe...
29840,Lenfant sauvage,Gojira,rock,2012,[Verse 1]\nSo long I've been trying to match\n...
32439,Silvera,Gojira,rock,2016,[Verse 1]\nQuit moaning about fate and change\...
36099,The Art of Dying,Gojira,rock,2008,"[Verse 1]\nBreathing slowly, mechanical heartb..."
...,...,...,...,...,...
1000782,Sentenced to Life,Gojira,rock,1996,Out in trash streets in the city\nLosers of th...
1058371,Escape,Gojira,pop,2015,"Feel no pain, but my life ain't easy\nI know I..."
1243718,On the B.O.T.A. Demo,Gojira,rock,1999,"Lost, a lion came and said:\n""Come, on the bri..."
1374662,Deliverance Demo,Gojira,rock,1999,"Your words are so cold to me\nIndisposed, don'..."
1973980,Maciste 14,Gojira,rock,2003,[???]\n\n[???]\n\nBut I got a neighbor there\n...